### ISSUE TITLE
進捗が出ない

### ISSUE THREAD

**Issue by mirukuma** [TeamPMG/CuteGirlsGenerator-Organized-#2]
つらい
やれることがもう殆どない

**Comment by jpnykw** [comment]
にゃーん 😿

**Comment by JPNYKW** [comment]
@MiL-B 
以下リスト内のチェックのツイたタスクを実行し、
チェックのツイていないタスクを終了して下さい。

- [x] 猫を愛でる
- [x] きつねをもふもふする
- [x] 可愛い女の子をもふもふする（したい）
- [ ] 機械学習をする
- [ ] インターネットをする
- [ ] PCをする

以下推奨されている開発環境です。
* 癒やしてくれる可愛い女の子またはペットがいる
* 美味しいものがすぐに食べられる状態にある

**Comment by jpnykw** [comment]
@MiL-B 
以下リスト内のチェックのツイたタスクを実行し、
チェックのツイていないタスクを終了して下さい。

- [x] 猫を愛でる
- [x] きつねをもふもふする
- [x] 可愛い女の子をもふもふする（したい）
- [ ] 機械学習をする
- [ ] インターネットをする
- [ ] PCをする

以下推奨されている開発環境です。
* 癒やしてくれる可愛い女の子またはペットがいる
* 美味しいものがすぐに食べられる状態にある

**Comment by mirukuma** [comment]
・猫がいません
・きつねがいません
・可愛い女の子もいません

どうしたらよいでしょう？

**Comment by jpnykw** [comment]
1. 猫を飼います
2. きつねを飼います
3. 可愛い女の子を飼います
4. **Be Happy🎉🎉🎉**

**Comment by mirukuma** [comment]
可愛い女の子に飼われたい場合はどうすればいいですか？
